version: "2"
linters:
  default: all
  disable:
    - err113                     # makes it impossible to use errors.New() in tests
    - embeddedstructfieldcheck   # subjective; can be useful to disambiguate
    - exhaustruct                # makes partial struct initialization impossible
    - funlen                     # subjective; prefer complexity metrics
    - gochecknoglobals           # subjective; there are legitimate uses for package variables
    - godot                      # not all comments need end with a period
    - inamedparam                # subjective; parameter names are not significant in interfaces though may be helpful
    - interfacebloat             # subjective
    - lll                        # long lines (> col 120) are (occasionally) acceptable/required
    - nlreturn                   # subjective
    - noinlineerr                # subjective; inline error checks sometimes help readability
    - paralleltest               # parallel tests are not always appropriate
    - varnamelen                 # excessively opinionated, subjective
    - wsl                        # unreasonably opinionated and buggy
    - wsl_v5                     # unreasonably opinionated and buggy

    # not supported when go.mod Go version is <1.22
    - copyloopvar
    - intrange

    # exceptions specific to the needs of this project
    - forbidigo           # Println is used to test stdout
    - ireturn             # returning any is required when dealing with types of unknown value
    - thelper                    # makes scenario exec(testing.T) test cases impossible

  settings:
    depguard:
      rules:
        tests:
          files:
            - $test
          list-mode: lax
          allow: ["*"]

    # disabled until I figure out a way to FAIL on a PR branch and only WARN on feature branches
    # godox:
    #   keywords:
    #     - TODO

    revive:
      rules:
        - name: package-comments
          disabled: true

    staticcheck:
      checks:
        - -QF1008    # "could remove embedded field <name> from selector"; sometimes it is useful (if unnecessary) to disambiguate
